src/api/urls.py
"""
urls.py
"""

from django.urls import path
from api.views.account_activated_view import AccountActivatedView
from api.views.base_view import BaseView
from api.views.change_password_view import ChangePasswordView
from api.views.classify_tile_view import ClassifyTileView
from api.views.get_classified_tiles_view import GetClassifiedTilesView
from api.views.guest_view import GuestView
from api.views.login_view import LoginView
from api.views.logout_view import LogoutView
from api.views.main_view import MainView
from api.views.manual_classification_view import ManualClassificationView
from api.views.password_changed_view import PasswordChangedView
from api.views.register_view import RegisterView
from api.views.send_activation_email_view import SendActivationEmailView
from api.views.send_change_password_email_view import SendChangePasswordEmailView
from api.views.transform_coordinates_view import TransformCoordinatesView

app_name = "urban_development"

urlpatterns = [
    path("", BaseView.as_view(),
         name="base_page"),
    path("guest/", GuestView.as_view(),
         name="guest_page"),
    path("login/", LoginView.as_view(),
         name="login_page"),
    path("logout/", LogoutView.as_view(),
         name="logout_page"),
    path("register/", RegisterView.as_view(),
         name="register_page"),
    path("send_activation_email/<slug:uid>/", SendActivationEmailView.as_view(),
         name="send_activation_email_page"),
    path("account_activated/<slug:uidb64>/<slug:token>/", AccountActivatedView.as_view(),
         name="account_activated_page"),
    path("change_password/", ChangePasswordView.as_view(),
         name="change_password_page"),
    path("send_change_password_email/<slug:uid>/", SendChangePasswordEmailView.as_view(),
         name="send_change_password_email_page"),
    path("password_changed/<slug:uidb64>/<slug:token>/", PasswordChangedView.as_view(),
         name="password_changed_page"),
    path("main/", MainView.as_view(),
         name="main_page"),
    path("get_classified_tiles/<parameters>/", GetClassifiedTilesView.as_view(),
         name="get_classified_tiles_page"),
    path("transform_coordinates/<parameters>/", TransformCoordinatesView.as_view(),
         name="transform_coordinates_page"),
    path("manual_classification/<parameters>/", ManualClassificationView.as_view(),
         name="manual_classification_page"),
    path("classify_tile/<parameters>/", ClassifyTileView.as_view(),
         name="classify_tile_page"),
]

src/urban_development/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("urban_development/", include("api.urls")),
    path("", RedirectView.as_view(url="urban_development/", permanent=True)),
]

src/api/forms/change_password_form.py
"""
change_password_form.py
"""

from django.contrib.auth.forms import PasswordResetForm
from django.core.exceptions import ObjectDoesNotExist
from api.models.user import User


class ChangePasswordForm(PasswordResetForm):
    """
    class ChangePasswordForm(PasswordResetForm)
    """

    class Meta:
        """
        class Meta
        """

        model = User
        fields = ("email", )

    def __init__(self, *args, **kwargs):
        """
        def __init__(self, *args, **kwargs)
        """

        super().__init__(*args, **kwargs)

        self.fields["email"].widget.attrs.update({"placeholder": "Email address"})
        self.fields["email"].widget.attrs.pop("autofocus", None)
        self.fields["email"].label = "Email address"

    def clean(self):
        """
        def clean(self)
        """

        cleaned_data = self.cleaned_data
        email = cleaned_data.get("email")

        try:
            User.objects.get(email=email)
        except ObjectDoesNotExist:
            self.add_error("email", "An account with that email address does not exist.")

        return cleaned_data

src/api/views/account_activated_view.py
"""
account_activated_view.py
"""

from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views import View
from api.models.user import User
from api.tokens import TOKEN_GENERATOR


class AccountActivatedView(View):
    """
    class AccountActivatedView(View)
    """

    _context = {
        "hyperlinks": {
            "Click here to log in": "/urban_development/login/",
        },
    }

    def get(self, request, uidb64, token):
        """
        def get(self, request, uidb64, token)
        """

        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, ObjectDoesNotExist):
            user = None

        if user is not None and TOKEN_GENERATOR.check_token(user, token):
            user.is_active = True
            user.save()
            self._context["title"] = "Account Activated Successfully"
            return render(request, "templates/user_data_template.html", context=self._context)

        self._context["title"] = "Invalid Activation Link"
        return render(request, "templates/user_data_template.html", context=self._context)

src/api/views/base_view.py
"""
base_view.py
"""

from django.shortcuts import redirect
from django.views import View


class BaseView(View):
    """
    class BaseView(View)
    """

    @staticmethod
    def get(request):
        """
        @staticmethod
        def get(request)
        """

        if request.user.is_authenticated:
            return redirect("urban_development:main_page")

        return redirect("urban_development:login_page")

src/api/views/change_password_view.py
"""
change_password_view.py
"""

from django.shortcuts import redirect, render
from django.views import View
from api.forms.change_password_form import ChangePasswordForm
from api.models.user import User


class ChangePasswordView(View):
    """
    class ChangePasswordView(View)
    """

    _context = {
        "title": "Change Password",
        "action": "/urban_development/change_password/",
        "hyperlinks": {
            "Click here to log in": "/urban_development/login/",
        },
        "button": "Change Password",
    }

    def get(self, request):
        """
        def get(self, request)
        """

        self._context["form"] = ChangePasswordForm()
        return render(request, "pages/register_and_change_password_page.html", context=self._context)

    def post(self, request):
        """
        def post(self, request)
        """

        form = ChangePasswordForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data.get("email")
            user = User.objects.get(email=email)
            return redirect("urban_development:send_change_password_email_page", uid=user.id)

        self._context["form"] = form
        return render(request, "pages/register_and_change_password_page.html", context=self._context)

src/api/views/classify_tile_view.py
"""
classify_tile_view.py
"""

import json
from django.http import JsonResponse
from django.views import View
from pyproj import Transformer
from api.utils.transform_coordinates_to_tile import transform_coordinates_to_tile
from api.utils.transform_tile_to_coordinates import transform_tile_to_coordinates
from classification.classifier_cnn import classify_cnn

LOW_MEDIUM_GREENERY = 0.33
MEDIUM_HIGH_GREENERY = 0.66


class ClassifyTileView(View):
    """
    class ClassifyTileView(View)
    """

    @staticmethod
    def get(_, parameters):
        """
        @staticmethod
        def get(_, parameters)
        """

        user = json.loads(parameters).get("user")

        if user == "guest":
            return JsonResponse(None, safe=False)

        year = json.loads(parameters).get("year")
        x_parameter = float(json.loads(parameters).get("longitude"))
        y_parameter = float(json.loads(parameters).get("latitude"))

        x_tile, y_tile = transform_coordinates_to_tile(x_parameter, y_parameter)

        tile_id = x_tile * 75879 + y_tile

        response = classify_cnn(year, tile_id)

        if response is None:
            return JsonResponse(None, safe=False)

        coordinates = transform_tile_to_coordinates(x_tile, y_tile)
        transformer = Transformer.from_crs("EPSG:28992", "EPSG:4326")
        center_x, center_y = transformer.transform(coordinates["x_coordinate"], coordinates["y_coordinate"])

        contains_greenery = response["contains_greenery"]
        greenery_percentage = response["greenery_percentage"]

        if contains_greenery != "unknown":
            if contains_greenery:
                if 0 <= greenery_percentage <= LOW_MEDIUM_GREENERY:
                    greenery_amount = "low"
                elif LOW_MEDIUM_GREENERY < greenery_percentage <= MEDIUM_HIGH_GREENERY:
                    greenery_amount = "medium"
                elif MEDIUM_HIGH_GREENERY < greenery_percentage <= 1:
                    greenery_amount = "high"
                else:
                    greenery_amount = "unknown"
            else:
                greenery_amount = "none"
        else:
            greenery_amount = "unknown"

        result = {
            "xmin": coordinates["xmin"],
            "ymin": coordinates["ymin"],
            "xmax": coordinates["xmax"],
            "ymax": coordinates["ymax"],
            "x_coordinate": center_x,
            "y_coordinate": center_y,
            "contains_greenery": contains_greenery,
            "greenery_amount": greenery_amount,
        }

        return JsonResponse(result, safe=False)

src/api/views/get_classified_tiles_view.py
"""
get_classified_tiles_view.py
"""

import json
from django.http import HttpResponseBadRequest, JsonResponse
from django.views import View
from pyproj import Transformer
from api.models.classification import Classification
from api.models.tile import Tile
from api.utils.transform_tile_to_coordinates import transform_tile_to_coordinates

PROVINCES = {"Drenthe": [75590, 75751, 75128, 75290], "Flevoland": [75424, 75574, 75228, 75391],
             "Friesland": [75380, 75641, 75043, 75240], "Gelderland": [75402, 75713, 75316, 75532],
             "Groningen": [75598, 75771, 75032, 75226], "Limburg": [75499, 75613, 75520, 75805],
             "Noord-Brabant": [75264, 75581, 75506, 75672], "Noord-Holland": [75205, 75455, 75133, 75552],
             "Overijssel": [75534, 75750, 75225, 75425], "Zuid-Holland": [75205, 75408, 75368, 75552],
             "Utrecht": [75368, 75509, 75376, 75498], "Zeeland": [75120, 75278, 75526, 75675]}

LOW_MEDIUM_GREENERY = 0.33
MEDIUM_HIGH_GREENERY = 0.66


class GetClassifiedTilesView(View):
    """
    class GetClassifiedTilesView(View)
    """

    @staticmethod
    def get(_, parameters):
        """
        @staticmethod
        def get(_, parameters)
        """

        year = json.loads(parameters).get("year")
        province = json.loads(parameters).get("province")

        if province == "None":
            classifications_for_year = Classification.objects.filter(year__lte=year).values("tile_id").distinct()
        else:
            x_min = PROVINCES.get(province)[0]
            x_max = PROVINCES.get(province)[1]
            y_min = PROVINCES.get(province)[2]
            y_max = PROVINCES.get(province)[3]

            tiles = Tile.objects.filter(x_coordinate__gte=x_min, x_coordinate__lte=x_max,
                                        y_coordinate__gte=y_min, y_coordinate__lte=y_max)
            classifications_for_year = Classification.objects.filter(year__lte=year, tile_id__in=tiles
                                                                     .values_list("tile_id", flat=True)).distinct()

        if len(classifications_for_year) <= 0:
            return HttpResponseBadRequest("No tiles have been classified for the selected year.")

        distinct_tiles = Tile.objects.filter(tile_id__in=classifications_for_year.values_list("tile_id", flat=True))

        transformer = Transformer.from_crs("EPSG:28992", "EPSG:4326")
        result = {}

        for tile in distinct_tiles:
            coordinates = transform_tile_to_coordinates(tile.x_coordinate, tile.y_coordinate)
            x_coordinate, y_coordinate = transformer.transform(coordinates["x_coordinate"], coordinates["y_coordinate"])

            result[tile.tile_id] = {
                "xmin": coordinates["xmin"],
                "ymin": coordinates["ymin"],
                "xmax": coordinates["xmax"],
                "ymax": coordinates["ymax"],
                "x_coordinate": x_coordinate,
                "y_coordinate": y_coordinate,
                "year": -1,
                "classified_by": "unknown",
                "contains_greenery": "unknown",
                "greenery_amount": "unknown",
            }

        for classification in classifications_for_year.values():
            if result[classification["tile_id"]]["year"] < classification["year"]:
                result[classification["tile_id"]]["year"] = classification["year"]

                if classification["classified_by"] == -1:
                    result[classification["tile_id"]]["classified_by"] = "classifier"
                elif classification["classified_by"] <= -2:
                    result[classification["tile_id"]]["classified_by"] = "training data"
                elif classification["classified_by"] > 0:
                    result[classification["tile_id"]]["classified_by"] = "user"
                else:
                    result[classification["tile_id"]]["classified_by"] = "unknown"

                result[classification["tile_id"]]["contains_greenery"] = classification["contains_greenery"]

                if classification["contains_greenery"]:
                    if 0 <= classification["greenery_percentage"] <= LOW_MEDIUM_GREENERY:
                        result[classification["tile_id"]]["greenery_amount"] = "low"
                    elif LOW_MEDIUM_GREENERY < classification["greenery_percentage"] <= MEDIUM_HIGH_GREENERY:
                        result[classification["tile_id"]]["greenery_amount"] = "medium"
                    elif MEDIUM_HIGH_GREENERY < classification["greenery_percentage"] <= 1:
                        result[classification["tile_id"]]["greenery_amount"] = "high"
                    else:
                        result[classification["tile_id"]]["greenery_amount"] = "unknown"
                else:
                    result[classification["tile_id"]]["greenery_amount"] = "none"

        return JsonResponse(list(result.values()), safe=False)

src/api/views/guest_view.py
"""
guest_view.py
"""

from django.contrib.auth import logout
from django.shortcuts import redirect
from django.views import View


class GuestView(View):
    """
    class GuestView(View)
    """

    @staticmethod
    def get(request):
        """
        @staticmethod
        def get(request)
        """

        logout(request)
        return redirect("urban_development:main_page")

src/api/views/login_view.py
"""
login_view.py
"""

from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from django.views import View
from api.forms.login_form import LoginForm


class LoginView(View):
    """
    class LoginView(View)
    """

    _context = {
        "title": "Login Page",
        "action": "/urban_development/login/",
        "hyperlinks": {
            "Click here to change your password": "/urban_development/change_password/",
            "Click here to register": "/urban_development/register/",
            "Log in as a guest": "/urban_development/guest/",
        },
        "button": "Log in",
    }

    def get(self, request):
        """
        def get(self, request)
        """

        self._context["form"] = LoginForm()
        return render(request, "pages/login_page.html", context=self._context)

    def post(self, request):
        """
        def post(self, request)
        """

        form = LoginForm(data=request.POST)

        if form.is_valid():
            data = form.cleaned_data
            email = data.get("username")
            password = data.get("password")
            user = authenticate(request, username=email, password=password)

            if user is not None:
                login(request, user)
                return redirect("urban_development:main_page")

        self._context["form"] = form
        return render(request, "pages/login_page.html", context=self._context)

src/api/views/logout_view.py
"""
logout_view.py
"""

from django.contrib.auth import logout
from django.shortcuts import redirect
from django.views import View


class LogoutView(View):
    """
    class LogoutView(View)
    """

    @staticmethod
    def get(request):
        """
        @staticmethod
        def get(request)
        """

        logout(request)
        return redirect("urban_development:login_page")

src/api/views/main_view.py
"""
main_view.py
"""

import collections
from django.shortcuts import render
from django.views import View
from api.utils.extract_available_years import extract_available_years


class MainView(View):
    """
    class MainView(View)
    """

    @staticmethod
    def get(request):
        """
        @staticmethod
        def get(request)
        """

        context = {
            "years": collections.OrderedDict(sorted(extract_available_years().items(), reverse=True)),
        }
        return render(request, "pages/main_page.html", context=context)

src/api/templates/pages/account_activation_email.html
{% extends "templates/email_template.html" %}

{% block body %}
Please use the following link to activate your Urban Development account:
http://{{ domain }}{% url "urban_development:account_activated_page" uidb64=uid token=token %}
{% endblock %}

src/api/templates/pages/change_password_email.html
{% extends "templates/email_template.html" %}

{% block body %}
Please use the following link to change the password associated with your Urban Development account:
http://{{ domain }}{% url "urban_development:password_changed_page" uidb64=uid token=token %}
{% endblock %}

src/api/templates/pages/login_page.html
{% extends "templates/user_data_template.html" %}

{% block imports %}
{% load static %}
<script type="text/javascript" src="{% static 'urban_development/js/login_page.js' %}"></script>
{% endblock %}

{% block form-error %}
<div class="{% if form.errors %}message error{% else %}hidden-row{% endif %}" id="form-error">
    {% if form.errors %}
    Invalid username or password.
    {% endif %}
</div>
{% endblock %}

src/api/templates/pages/main_page.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="description" content="Urban Development">
        <meta name="author" content="Group 18A">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Urban Development</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="https://js.arcgis.com/4.15/esri/themes/dark-blue/main.css">
        <link rel="stylesheet" type="text/css" href="{% static 'urban_development/css/main_page.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'urban_development/css/global.css' %}">
        <script src="https://js.arcgis.com/4.15/"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="{% static 'urban_development/js/main_page.js' %}" type="text/javascript"></script>
    </head>
    <body>
        <div class="page-container">
            <div class="title-container">
                <div class="navbar" id="main-page-header">
                    <img src="{% static 'urban_development/images/logo2.png' %}" class="logo">
                    <nav>
                        <div class="nav-left">
                            <div class="text-center">
                                <a class="text-element" id="how-to-view-button">
                                    How to use
                                </a>
                            </div>
                            <div class="text-center">
                                <a class="text-element" id="map-view-button">
                                    Map view
                                </a>
                            </div>
                            <div class="text-center">
                                <a class="text-element" id="data-view-button">
                                    Data view
                                </a>
                            </div>
                            <div class="text-center" id="year-cell">
                                <span class="text-element">
                                    Year
                                </span>
                                <br>
                                <select name="year" class="text-element" id="year">
                                    {% for key, value in years.items %}
                                    <option value="{{ value }}">
                                        {{ key }}
                                    </option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="text-center" id="overlay-cell">
                                <span class="text-element">
                                    Overlay
                                </span>
                                <br>
                                <select name="overlay" class="text-element" id="overlay">
                                    <option value="None">None</option>
                                    <option value="Classified as">Classified as</option>
                                    <option value="Classified by">Classified by</option>
                                </select>
                            </div>
                            <div class="text-center hidden" id="province-cell">
                                <span class="text-element">
                                    Province
                                </span>
                                <br>
                                <select name="province" class="text-element" id="province">
                                    <option value="None">All</option>
                                    <option value="Drenthe">Drenthe</option>
                                    <option value="Flevoland">Flevoland</option>
                                    <option value="Friesland">Friesland</option>
                                    <option value="Gelderland">Gelderland</option>
                                    <option value="Groningen">Groningen</option>
                                    <option value="Limburg">Limburg</option>
                                    <option value="Noord-Brabant">Noord-Brabant</option>
                                    <option value="Noord-Holland">Noord-Holland</option>
                                    <option value="Overijssel">Overijssel</option>
                                    <option value="Zuid-Holland">Zuid-Holland</option>
                                    <option value="Utrecht">Utrecht</option>
                                    <option value="Zeeland">Zeeland </option>
                                </select>
                            </div>
                        </div>
                        <div id="email-cell">
                            <div>
                                <span class="text-element" id="user-name">
                                    Hello,
                                    {% if user.is_authenticated %}
                                    {{ user.email }}
                                    {% else %}
                                    guest
                                    {% endif %}
                                </span>
                                <br>
                                {% if user.is_authenticated %}
                                <a href="/urban_development/logout/" class="text-element" id="logout-hyperlink">
                                    Log out
                                </a>
                                {% else %}
                                <a href="/urban_development/login/" class="text-element" id="logout-hyperlink">
                                    Log in
                                </a>
                                {% endif %}
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </body>
</html>

src/api/templates/pages/register_and_change_password_page.html
{% extends "templates/user_data_template.html" %}

{% block imports %}
{% load static %}
<script type="text/javascript" src="{% static 'urban_development/js/registration_and_change_password_page.js' %}"></script>
{% endblock %}

{% block input-error %}
<div class="{% if field.errors %}message error{% else %}hidden-row{% endif %}">
    {{ field.errors.0 }}
</div>
{% endblock %}